# Create Events Page HTML with Calendar and Filters
events_html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Events - Chhath Utsav Mahasangh</title>
    <link rel="stylesheet" href="styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
    <!-- Header -->
    <header class="header">
        <div class="container">
            <nav class="nav">
                <a href="index.html" class="logo">🪔 Chhath Utsav Mahasangh</a>
                <ul class="nav-links">
                    <li><a href="index.html">Home</a></li>
                    <li><a href="about-us.html">About Us</a></li>
                    <li><a href="about-chhath.html">About Chhath</a></li>
                    <li><a href="events.html" class="active">Events</a></li>
                    <li><a href="gallery.html">Gallery</a></li>
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="contact.html">Contact</a></li>
                    <li><a href="donate.html" class="btn btn-secondary">Donate</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <!-- Hero Section -->
    <section class="hero">
        <div class="container">
            <h1>📅 Events & Calendar</h1>
            <p>Stay updated with all our celebrations, workshops, and community activities</p>
        </div>
    </section>

    <!-- Event Filters -->
    <section class="section" style="padding-top: 2rem; padding-bottom: 2rem;">
        <div class="container">
            <div class="filters">
                <button class="filter-btn active" data-filter="all">All Events</button>
                <button class="filter-btn" data-filter="puja">Puja Celebrations</button>
                <button class="filter-btn" data-filter="workshop">Workshops</button>
                <button class="filter-btn" data-filter="cultural">Cultural Programs</button>
                <button class="filter-btn" data-filter="community">Community Service</button>
                <button class="filter-btn" data-filter="ghat">Ghat Events</button>
            </div>
        </div>
    </section>

    <!-- Calendar Section -->
    <section class="section" style="padding-top: 0;">
        <div class="container">
            <div class="grid grid-2">
                <!-- Calendar Widget -->
                <div class="calendar">
                    <div class="calendar-header">
                        <div class="calendar-nav">
                            <button id="prevMonth">‹</button>
                            <h3 id="monthYear">November 2024</h3>
                            <button id="nextMonth">›</button>
                        </div>
                    </div>
                    <div class="calendar-grid">
                        <div class="calendar-day" style="font-weight: bold; background: var(--primary-color); color: white;">Sun</div>
                        <div class="calendar-day" style="font-weight: bold; background: var(--primary-color); color: white;">Mon</div>
                        <div class="calendar-day" style="font-weight: bold; background: var(--primary-color); color: white;">Tue</div>
                        <div class="calendar-day" style="font-weight: bold; background: var(--primary-color); color: white;">Wed</div>
                        <div class="calendar-day" style="font-weight: bold; background: var(--primary-color); color: white;">Thu</div>
                        <div class="calendar-day" style="font-weight: bold; background: var(--primary-color); color: white;">Fri</div>
                        <div class="calendar-day" style="font-weight: bold; background: var(--primary-color); color: white;">Sat</div>
                        
                        <!-- Calendar dates will be generated by JavaScript -->
                        <div class="calendar-day"></div>
                        <div class="calendar-day"></div>
                        <div class="calendar-day"></div>
                        <div class="calendar-day"></div>
                        <div class="calendar-day">1</div>
                        <div class="calendar-day">2</div>
                        <div class="calendar-day">3</div>
                        <div class="calendar-day">4</div>
                        <div class="calendar-day">5</div>
                        <div class="calendar-day has-event">6<span style="font-size: 0.7rem; display: block;">Workshop</span></div>
                        <div class="calendar-day has-event">7<span style="font-size: 0.7rem; display: block;">Nahay Khay</span></div>
                        <div class="calendar-day has-event">8<span style="font-size: 0.7rem; display: block;">Kharna</span></div>
                        <div class="calendar-day has-event">9<span style="font-size: 0.7rem; display: block;">Sandhya Arghya</span></div>
                        <div class="calendar-day has-event">10<span style="font-size: 0.7rem; display: block;">Usha Arghya</span></div>
                        <div class="calendar-day">11</div>
                        <div class="calendar-day">12</div>
                        <div class="calendar-day">13</div>
                        <div class="calendar-day">14</div>
                        <div class="calendar-day has-event">15<span style="font-size: 0.7rem; display: block;">Cleanup</span></div>
                        <div class="calendar-day">16</div>
                        <div class="calendar-day">17</div>
                        <div class="calendar-day">18</div>
                        <div class="calendar-day">19</div>
                        <div class="calendar-day has-event">20<span style="font-size: 0.7rem; display: block;">Cultural Program</span></div>
                        <div class="calendar-day">21</div>
                        <div class="calendar-day">22</div>
                        <div class="calendar-day">23</div>
                        <div class="calendar-day">24</div>
                        <div class="calendar-day">25</div>
                        <div class="calendar-day">26</div>
                        <div class="calendar-day">27</div>
                        <div class="calendar-day">28</div>
                        <div class="calendar-day">29</div>
                        <div class="calendar-day">30</div>
                    </div>
                </div>

                <!-- Upcoming Events Summary -->
                <div class="card">
                    <h3>Upcoming Highlights</h3>
                    <div style="margin-top: 1rem;">
                        <div style="border-left: 4px solid var(--primary-color); padding-left: 1rem; margin-bottom: 1.5rem;">
                            <h4>Chhath Puja 2024</h4>
                            <p style="color: var(--text-light);">November 7-10, 2024</p>
                            <p>Four-day grand celebration at Juhu Beach</p>
                        </div>
                        <div style="border-left: 4px solid var(--secondary-color); padding-left: 1rem; margin-bottom: 1.5rem;">
                            <h4>Pre-Puja Workshop</h4>
                            <p style="color: var(--text-light);">November 6, 2024</p>
                            <p>Learn rituals and traditions</p>
                        </div>
                        <div style="border-left: 4px solid var(--accent-color); padding-left: 1rem;">
                            <h4>Beach Cleanup Drive</h4>
                            <p style="color: var(--text-light);">November 15, 2024</p>
                            <p>Post-festival environmental care</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Event Details Section -->
    <section class="section" style="background-color: var(--bg-light);">
        <div class="container">
            <h2 class="section-title">Detailed Event Schedule</h2>
            
            <!-- Chhath Puja Main Events -->
            <div class="event-item" data-category="puja ghat">
                <div class="card" style="border-left: 6px solid var(--primary-color);">
                    <div class="grid grid-2">
                        <div>
                            <h3>🌅 Chhath Puja - Day 1 (Nahay Khay)</h3>
                            <p><strong>📅 Date:</strong> November 7, 2024</p>
                            <p><strong>📍 Location:</strong> Juhu Beach, Mumbai</p>
                            <p><strong>⏰ Time:</strong> 6:00 AM - 8:00 PM</p>
                            <p>The first day of purification and preparation. Devotees take holy baths and consume sattvic food.</p>
                        </div>
                        <div style="text-align: right;">
                            <p style="color: var(--text-light); margin-bottom: 1rem;">Expected Attendance: 10,000+</p>
                            <button class="btn btn-primary" onclick="openRSVP('nahay-khay')">Register / RSVP</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="event-item" data-category="puja ghat">
                <div class="card" style="border-left: 6px solid var(--primary-color);">
                    <div class="grid grid-2">
                        <div>
                            <h3>🌙 Chhath Puja - Day 2 (Kharna)</h3>
                            <p><strong>📅 Date:</strong> November 8, 2024</p>
                            <p><strong>📍 Location:</strong> Juhu Beach, Mumbai</p>
                            <p><strong>⏰ Time:</strong> 5:00 AM - 10:00 PM</p>
                            <p>Day-long fasting followed by evening moon worship and prasad distribution.</p>
                        </div>
                        <div style="text-align: right;">
                            <p style="color: var(--text-light); margin-bottom: 1rem;">Expected Attendance: 15,000+</p>
                            <button class="btn btn-primary" onclick="openRSVP('kharna')">Register / RSVP</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="event-item" data-category="puja ghat">
                <div class="card" style="border-left: 6px solid var(--primary-color);">
                    <div class="grid grid-2">
                        <div>
                            <h3>🌅 Chhath Puja - Day 3 (Sandhya Arghya)</h3>
                            <p><strong>📅 Date:</strong> November 9, 2024</p>
                            <p><strong>📍 Location:</strong> Juhu Beach, Mumbai</p>
                            <p><strong>⏰ Time:</strong> 4:00 PM - 8:00 PM</p>
                            <p>Evening offering to the setting sun. The most spectacular day with thousands in the water.</p>
                        </div>
                        <div style="text-align: right;">
                            <p style="color: var(--text-light); margin-bottom: 1rem;">Expected Attendance: 50,000+</p>
                            <button class="btn btn-primary" onclick="openRSVP('sandhya-arghya')">Register / RSVP</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="event-item" data-category="puja ghat">
                <div class="card" style="border-left: 6px solid var(--primary-color);">
                    <div class="grid grid-2">
                        <div>
                            <h3>🌞 Chhath Puja - Day 4 (Usha Arghya)</h3>
                            <p><strong>📅 Date:</strong> November 10, 2024</p>
                            <p><strong>📍 Location:</strong> Juhu Beach, Mumbai</p>
                            <p><strong>⏰ Time:</strong> 5:00 AM - 9:00 AM</p>
                            <p>Dawn offering to the rising sun and completion of the sacred vrat.</p>
                        </div>
                        <div style="text-align: right;">
                            <p style="color: var(--text-light); margin-bottom: 1rem;">Expected Attendance: 45,000+</p>
                            <button class="btn btn-primary" onclick="openRSVP('usha-arghya')">Register / RSVP</button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Workshop Events -->
            <div class="event-item" data-category="workshop">
                <div class="card" style="border-left: 6px solid var(--secondary-color);">
                    <div class="grid grid-2">
                        <div>
                            <h3>📚 Pre-Puja Cultural Workshop</h3>
                            <p><strong>📅 Date:</strong> November 6, 2024</p>
                            <p><strong>📍 Location:</strong> Community Hall, Andheri</p>
                            <p><strong>⏰ Time:</strong> 6:00 PM - 8:00 PM</p>
                            <p>Learn the significance, rituals, and traditional songs of Chhath Puja from experienced practitioners.</p>
                        </div>
                        <div style="text-align: right;">
                            <p style="color: var(--text-light); margin-bottom: 1rem;">Capacity: 200 people</p>
                            <button class="btn btn-primary" onclick="openRSVP('workshop')">Register / RSVP</button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Cultural Events -->
            <div class="event-item" data-category="cultural">
                <div class="card" style="border-left: 6px solid var(--accent-color);">
                    <div class="grid grid-2">
                        <div>
                            <h3>🎵 Chhath Folk Music Evening</h3>
                            <p><strong>📅 Date:</strong> November 20, 2024</p>
                            <p><strong>📍 Location:</strong> Shivaji Park</p>
                            <p><strong>⏰ Time:</strong> 7:00 PM - 9:00 PM</p>
                            <p>Traditional folk music and cultural performances celebrating the essence of Chhath.</p>
                        </div>
                        <div style="text-align: right;">
                            <p style="color: var(--text-light); margin-bottom: 1rem;">Free Entry</p>
                            <button class="btn btn-primary" onclick="openRSVP('cultural-program')">Register / RSVP</button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Community Service Events -->
            <div class="event-item" data-category="community">
                <div class="card" style="border-left: 6px solid #10b981;">
                    <div class="grid grid-2">
                        <div>
                            <h3>🌊 Beach Cleanup Drive</h3>
                            <p><strong>📅 Date:</strong> November 15, 2024</p>
                            <p><strong>📍 Location:</strong> Juhu Beach</p>
                            <p><strong>⏰ Time:</strong> 7:00 AM - 10:00 AM</p>
                            <p>Post-festival beach cleaning and environmental restoration activity.</p>
                        </div>
                        <div style="text-align: right;">
                            <p style="color: var(--text-light); margin-bottom: 1rem;">Volunteers Needed: 100</p>
                            <button class="btn btn-primary" onclick="openRSVP('cleanup')">Register / RSVP</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- RSVP Modal -->
    <div id="rsvpModal" style="display: none; position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.5); z-index: 1000; justify-content: center; align-items: center;">
        <div class="card" style="max-width: 500px; margin: 2rem; max-height: 90vh; overflow-y: auto;">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem;">
                <h3 id="modalTitle">Event Registration</h3>
                <button onclick="closeRSVP()" style="background: none; border: none; font-size: 1.5rem; cursor: pointer;">&times;</button>
            </div>
            <form id="rsvpForm">
                <div class="form-group">
                    <label class="form-label">Full Name *</label>
                    <input type="text" class="form-input" required>
                </div>
                <div class="form-group">
                    <label class="form-label">Email Address *</label>
                    <input type="email" class="form-input" required>
                </div>
                <div class="form-group">
                    <label class="form-label">Phone Number *</label>
                    <input type="tel" class="form-input" required>
                </div>
                <div class="form-group">
                    <label class="form-label">Number of Attendees</label>
                    <select class="form-select">
                        <option value="1">1 Person</option>
                        <option value="2">2 People</option>
                        <option value="3">3 People</option>
                        <option value="4">4 People</option>
                        <option value="5+">5+ People</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-label">Special Requirements</label>
                    <textarea class="form-textarea" rows="3" placeholder="Any special needs or requirements..."></textarea>
                </div>
                <button type="submit" class="btn btn-primary" style="width: 100%;">Confirm Registration</button>
            </form>
        </div>
    </div>

    <!-- JavaScript for Interactivity -->
    <script>
        // Filter functionality
        document.querySelectorAll('.filter-btn').forEach(btn => {
            btn.addEventListener('click', () => {
                // Remove active class from all buttons
                document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
                // Add active class to clicked button
                btn.classList.add('active');
                
                const filter = btn.dataset.filter;
                const events = document.querySelectorAll('.event-item');
                
                events.forEach(event => {
                    if (filter === 'all' || event.dataset.category.includes(filter)) {
                        event.style.display = 'block';
                    } else {
                        event.style.display = 'none';
                    }
                });
            });
        });

        // RSVP Modal functions
        function openRSVP(eventType) {
            const modal = document.getElementById('rsvpModal');
            const title = document.getElementById('modalTitle');
            
            const eventTitles = {
                'nahay-khay': 'Chhath Puja - Day 1 (Nahay Khay)',
                'kharna': 'Chhath Puja - Day 2 (Kharna)',
                'sandhya-arghya': 'Chhath Puja - Day 3 (Sandhya Arghya)',
                'usha-arghya': 'Chhath Puja - Day 4 (Usha Arghya)',
                'workshop': 'Pre-Puja Cultural Workshop',
                'cultural-program': 'Chhath Folk Music Evening',
                'cleanup': 'Beach Cleanup Drive'
            };
            
            title.textContent = eventTitles[eventType] || 'Event Registration';
            modal.style.display = 'flex';
            document.body.style.overflow = 'hidden';
        }

        function closeRSVP() {
            document.getElementById('rsvpModal').style.display = 'none';
            document.body.style.overflow = 'auto';
        }

        // Form submission
        document.getElementById('rsvpForm').addEventListener('submit', (e) => {
            e.preventDefault();
            alert('Thank you for registering! You will receive a confirmation email shortly.');
            closeRSVP();
        });

        // Close modal when clicking outside
        document.getElementById('rsvpModal').addEventListener('click', (e) => {
            if (e.target.id === 'rsvpModal') {
                closeRSVP();
            }
        });
    </script>

    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            <div class="footer-content">
                <div class="footer-section">
                    <h3>Contact Info</h3>
                    <p>📍 Juhu Beach, Mumbai</p>
                    <p>📞 +91 98765 43210</p>
                    <p>✉️ info@chhathutsav.org</p>
                </div>
                <div class="footer-section">
                    <h3>Quick Links</h3>
                    <p><a href="about-us.html">About Our Organization</a></p>
                    <p><a href="about-chhath.html">About Chhath Puja</a></p>
                    <p><a href="gallery.html">Photo Gallery</a></p>
                    <p><a href="blog.html">Latest News</a></p>
                </div>
                <div class="footer-section">
                    <h3>Get Involved</h3>
                    <p><a href="contact.html">Volunteer With Us</a></p>
                    <p><a href="donate.html">Make a Donation</a></p>
                    <p><a href="#">Join Newsletter</a></p>
                    <p><a href="#">Share Our Mission</a></p>
                </div>
            </div>
            <div class="footer-bottom">
                <p>&copy; 2024 Chhath Utsav Mahasangh. Serving devotion, culture & community since 1993.</p>
            </div>
        </div>
    </footer>
</body>
</html>"""

# Save the Events page
with open('events.html', 'w', encoding='utf-8') as f:
    f.write(events_html)

print("Created events.html")